default_context:
  project_name: 'AuthFlowX'
  project_slug: 'authflowx'
  domain_main: 'authflowx.com'
  domain_staging: 'stag.authflowx.com'
  docker_swarm_stack_name_main: 'authflowx-com'
  docker_swarm_stack_name_staging: 'stag-authflowx-com'
  secret_key: 'df411a817a1c2f89f8452e8e6d1663466c39b80f179ca130b6bb285141b3978e'
  first_superuser: 'admin@authflowx.com'
  first_superuser_password: 'admin1234'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.authflowx.com", "https://stag.authflowx.com", "https://authflowx.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.ethereal.email'
  smtp_user: 'Callie Harvey'
  smtp_password: 'Ga88N7jVkYy24Nujmq'
  smtp_emails_from_email: 'info@authflowx.com'
  postgres_password: 'akachipostgres123'
  pgadmin_default_user: 'admin@authflowx.com'
  pgadmin_default_user_password: 'admin1234'
  traefik_constraint_tag: 'authflowx.com'
  traefik_constraint_tag_staging: 'stag.authflowx.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin1234'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
