services:
  - name: proxy
    image: traefik:v2.2
    env:
      - TRAEFIK_TAG=${TRAEFIK_TAG}
      - DOMAIN=${DOMAIN}
      # Add other environment variables here as needed
    secrets:
      - name: TRAEFIK_PUBLIC_NETWORK
        path: /var/run/docker.sock
    ports:
      - 80
      - 443
    startCommand: ["traefik", "--configFile", "/etc/traefik/traefik.toml"]
    healthCheck:
      path: /
      port: 80
    instanceCount: 1

  - name: db
    image: postgres:12
    env:
      - PGDATA=/var/lib/postgresql/data/pgdata
      # Add other environment variables here as needed
    secrets:
      - name: .env
    ports:
      - 5432
    healthCheck:
      path: /
      port: 5432
    instanceCount: 1

  - name: pgadmin
    image: dpage/pgadmin4
    env:
      # Add environment variables here as needed
    secrets:
      - name: .env
    ports:
      - 5050
    dependsOn:
      - service: db
    healthCheck:
      path: /
      port: 5050
    instanceCount: 1

  - name: queue
    image: rabbitmq:3

  - name: flower
    image: mher/flower
    env:
      - BROKER=amqp://guest@queue:5672//
      # Add other environment variables here as needed
    secrets:
      - name: .env
    ports:
      - 5555
    healthCheck:
      path: /
      port: 5555
    instanceCount: 1

  - name: backend
    image: ${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}
    env:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Add other environment variables here as needed
    secrets:
      - name: .env
    healthCheck:
      path: /
      port: 80
    instanceCount: 1

  - name: celeryworker
    image: ${DOCKER_IMAGE_CELERYWORKER?Variable not set}:${TAG-latest}
    env:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Add other environment variables here as needed
    secrets:
      - name: .env
    healthCheck:
      path: /
      port: 80
    instanceCount: 1

  - name: frontend
    image: ${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}
    env:
      - FRONTEND_ENV=production
      # Add other environment variables here as needed
    healthCheck:
      path: /
      port: 80
    instanceCount: 1

databases:
  - name: app-db-data

networks:
  - name: traefik-public
    external: ${TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL-true}
